sudo ln -s /home/tom/Scripts/autostart.sh  /usr/local/bin/autostart
sudo ln -s /home/tom/Scripts/appinstall.sh /usr/local/bin/appinstall
sudo ln -s /home/tom/Scripts/backingup.sh /usr/local/bin/backmyshitup
sudo ln -s /home/tom/Scripts/cantconnect.sh /usr/local/bin/cantconnect
sudo ln -s /home/tom/Scripts/dovahcow.sh /usr/local/bin/dovahcow
sudo ln -s /home/tom/Scripts/inet.sh /usr/local/bin/inet
sudo ln -s /home/tom/Scripts/search.sh /usr/local/bin/search
sudo ln -s /home/tom/Scripts/services.sh /usr/local/bin/services
sudo ln -s /home/tom/Scripts/space.sh /usr/local/bin/space
sudo ln -s /home/tom/Scripts/UpgradeTime.sh /usr/local/bin/upgradetime
sudo ln -s /home/tom/Scripts/wan.sh /usr/local/bin/wan
sudo ln -s /home/tom/Scripts/weather.sh /usr/local/bin/weather
sudo ln -s /home/tom/Scripts/home.sh /usr/local/bin/home
